pub const SQUARE_SIZE: f32 = 35.0;
pub const BORDER_SIZE: f32 = 1.0;
pub const BOARD_WIDTH: f32 = SQUARE_SIZE * 10.0;
pub const BOARD_HEIGHT: f32 = SQUARE_SIZE * 18.0;
pub const WINDOW_WIDTH: f32 = BOARD_WIDTH + 9.0 * SQUARE_SIZE;
pub const WINDOW_HEIGHT: f32 = BOARD_HEIGHT + 2.0 * SQUARE_SIZE;
pub const ENTRY_POINT: (f32, f32) = (SQUARE_SIZE, SQUARE_SIZE);

pub const SINGLE_LINE_POINTS: i32 = 40;
pub const DOUBLE_LINE_POINTS: i32 = 100;
pub const TRIPLE_LINE_POINTS: i32 = 300;
pub const TETRIS_POINTS: i32 = 1200;