pub static SQUARE_SIZE: f32 = 40.0;
pub static BORDER_SIZE: f32 = 1.0;
pub static BOARD_WIDTH: f32 = SQUARE_SIZE * 10.0;
pub static BOARD_HEIGHT: f32 = SQUARE_SIZE * 20.0;
pub static WINDOW_WIDTH: f32 = BOARD_WIDTH + (2.0 * SQUARE_SIZE) + (6.0 * SQUARE_SIZE);
pub static WINDOW_HEIGHT: f32 = BOARD_HEIGHT + 2.0 * SQUARE_SIZE;
pub static ROTATION_INTERVAL: i32 = 4;
pub static MOVE_INTERVAL: i32 = 2;
pub static ENTRY_POINT: (f32, f32) = (SQUARE_SIZE, SQUARE_SIZE);